-- H2 전용(dev/test 프로파일): 시드가 명시 ID로 INSERT하면 IDENTITY 시퀀스가 갱신되지 않아
-- 이후 신규 INSERT(회원가입/글작성 등)에서 PK 충돌이 발생한다. 시퀀스를 시드 최대값 위로 리셋.
-- (prod 프로파일은 sql.init.mode=never 라 이 스크립트가 실행되지 않음 → MySQL과 무관)
ALTER TABLE users ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE community ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE comment ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE files ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE refresh_entity ALTER COLUMN id RESTART WITH 1000;
-- 코스 학습 테이블: 코스별 시드 ID 대역(설계 §7-8 — N5 1~999 / N4 1000~ / N3 2000~ / N2 3000~,
-- 향후 입문 4000~ / N1 5000~)을 쓰므로 리셋 값은 대역 전체 위인 10000. (런타임 INSERT는 없지만 안전값 유지)
ALTER TABLE course ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE course_unit ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE grammar_point ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE grammar_example ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE grammar_rule ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE dialog ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE dialog_line ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE kanji ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE kanji_word ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE vocabulary ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE unit_grammar ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE unit_kanji ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE unit_vocabulary ALTER COLUMN id RESTART WITH 10000;
-- 영어 과정(설계/03 §7-3) — 런타임 INSERT는 없지만 다른 콘텐츠 테이블과 같은 규칙을 유지한다.
ALTER TABLE expression ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE expression_example ALTER COLUMN id RESTART WITH 10000;
ALTER TABLE unit_expression ALTER COLUMN id RESTART WITH 10000;
